# Site settings
title: MultiBoot USB
description: >
  This is a collection of GRUB scripts that allows to create a bootable pendrive
  (USB dongle, flash stick) supporting a number of different OS images.
  Simply copy ISO files under `/iso-imgs`.
  Both UEFI and Legacy BIOS boot modes can be enabled simultaneously.
baseurl: ""
url: "https://mbusb.aguslr.com"
repository: ulidtko/multibootusb

# GitHub
github:
  owner_name: ulidtko
  owner_url: https://github.com/ulidtko
  repository_url: https://github.com/ulidtko/multibootusb
  tar_url: https://github.com/ulidtko/multibootusb/archive/opensource.tar.gz
  zip_url: https://github.com/ulidtko/multibootusb/archive/opensource.zip

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

# Theme settings
show_downloads: true

# Kramdown settings
kramdown:
  syntax_highlighter_opts:
    default_lang: shell

# Collections
collections:
  android:
    output: true
  linux:
    output: true
  unix:
    output: true
  misc:
    output: true
